apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

configMapGenerator:
- literals:
  - main.conf=| color=cornflower_blue log_level=info
  name: conf

# components:
# - ../components/external_db
