apiVersion: batch/v1
kind: Job
metadata:
  name: postdelete-hook
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: postdelete-hook
    spec:
        containers:
          - command:
              - "true"
            image: quay.io/argoprojlabs/argocd-e2e-container:0.1
            imagePullPolicy: IfNotPresent
            name: main
        restartPolicy: Never