apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  annotations:
    # Enable Server-Side Diff.
    # Server-Side Diff does not include changes made by mutation webhooks by default.
    # argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: kyverno
    name: in-cluster
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: v3.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    # Fix one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io
    # "clusterpolicies.kyverno.io" is invalid: metadata.annotations: Too long: must have at most 262144"
    - ServerSideApply=true